V8_INC=../v8/include
V8_LIB=../v8/out/x64.release/lib.target

CC=g++
CFLAGS=-c -fPIC -I$(V8_INC)
LDFLAGS=-shared -L$(V8_LIB) -lv8 -lc
SOURCES=v8wrapper.cc
OBJECTS=$(SOURCES:.cc=.o)
TARGET=libv8wrapper.so

all: $(TARGET)
	
clean:
	rm -f *.o *.so *.dylib

.cc.o:
	$(CC) $(CFLAGS) $< -o $@

$(TARGET): $(OBJECTS)
	ld $(LDFLAGS) $(OBJECTS) -o $(TARGET)

